parameters:
    pim_magento_connector.factory.magento_soap_client.class: Pim\Bundle\MagentoConnectorBundle\Webservice\MagentoSoapClientFactory
    pim_magento_connector.webservice.url_explorer.class:     Pim\Bundle\MagentoConnectorBundle\Webservice\UrlExplorer
    pim_magento_connector.webservice.magento_soap_client_parameters_registry.class: Pim\Bundle\MagentoConnectorBundle\Webservice\MagentoSoapClientParametersRegistry
    pim_magento_connector.service.guzzle.client.class:       Guzzle\Service\Client

services:
    pim_magento_connector.webservice.url_explorer:
        class: %pim_magento_connector.webservice.url_explorer.class%
        arguments:
            - '@pim_magento_connector.web_client.guzzle'

    pim_magento_connector.webservice.magento_soap_client_parameters_registry:
        class: %pim_magento_connector.webservice.magento_soap_client_parameters_registry.class%

    pim_magento_connector.factory.magento_soap_client:
        class: %pim_magento_connector.factory.magento_soap_client.class%

    pim_magento_connector.web_client.guzzle:
        class: '%pim_magento_connector.service.guzzle.client.class%'
        tags:
            - { name: guzzle.client }
